import { Middleware, Dispatch, Action } from 'redux';
import { UserManager } from 'oidc-client';
import FinalUser from './FinalUser';
export declare let storedUser: any;
export declare let nextMiddleware: any;
export declare function setNext(newNext: Middleware): void;
export declare function getNext(): Middleware;
export declare function setStoredUser(user: FinalUser): void;
export declare function removeStoredUser(): void;
export declare function getUserCallback(user: FinalUser): void;
export declare function errorCallback(error: Error): void;
export declare const middlewareHandler: (userManager: UserManager) => Middleware<{}, any, Dispatch<Action<any>>>;
export default function createOidcMiddleware(userManager: UserManager): Middleware;
